version: '3'

services:
  redis:
    image: 'redis:7.2.4'
    ports:
      - 6379:6379
  pixel-service:
    build: ./PixelService
    ports: 
      - 8088:8080
    environment:
      - Redis__Endpoint=redis
  storage-service:
    build: ./StorageService
    environment:
      - Redis__Endpoint=redis
      - FilePath=/logs/visits.log
    volumes:
      - ./logs:/logs
